# Default values for zipkin.
collector:
  replicaCount: 3
  maxReplicaCount: 5
  targetCPUUtilizationPercentage: 80
  imageVersion: 2
  sampleRate: 0.1
  probeStartupDelay: 200
  queryPort: 9411
  resources:
    ramMb: 1100
    javaOptsHeap: 1000
    cpuRequest: 80m
    cpuLimit: 300m

ui:
  replicaCount: 1
  imageVersion: 2
  probeStartupDelay: 200
  queryPort: 9411
  resources:
    ramMb: 900
    javaOptsHeap: 700
    cpuRequest: 150m
    cpuLimit: 600m

dependencies:
  enabled: true
  cron: "0 22 * * *"
  imageVersion: 1.11.0
  resources:
    ramMbLimits: 4000
    ramMbRequests: 4000
    javaOptsHeap: 3500
    cpuRequest: 1
    cpuLimit: 1

configmap:
  name: zipkin-storage
  contactPoints:
    name: zipkin-storage
    key: cassandra.contactpoints
  username:
    name: zipkin-storage
    key: cassandra.username
  localdc:
    name: zipkin-storage
    key: cassandra.localdc

ingress:
  class: "nginx"
  path: /
  serviceName: zipkin-ui
  servicePort: 9411

storageMethod: cassandra3

cassandra:
  username: zipkin
  password: zipkin
  contactPoints: zipkin-cassandra:9042
  localdc: datacenter1
  ensureSchema: false
  image: openzipkin/zipkin-cassandra
  probeStartupDelay: 120
  tag: 2
  replicas: 1
  pvSize: 20Gi
  resources:
    ramMbRequest: 3000
    ramMbLimit: 8000
    cpuRequest: 200m
    cpuLimit: 500m

node:
  cpus: 2


