apiVersion: v1
kind: Secret
metadata:
  name: votes-ai
type: Opaque
data:
  ACCESS_TOKEN: ${base64Encode(var.ACCESS_TOKEN)}
  OPENAI_API_KEY: ${base64Encode(var.OPENAI_API_KEY)}
  OPENAI_ORGANIZATION: ${base64Encode(var.OPENAI_ORGANIZATION)}
