version: '3.9'

services:
  bundestag-io:
    build:
      context: bundestag.io/api
      target: build_stage
    command: yarn run dev
    volumes:
      - ./bundestag.io/api:/app
      - /app/node_modules
  bio-admin:
    build:
      context: bundestag.io/admin
      target: deps
    command: yarn run dev
    volumes:
      - ./bundestag.io/admin:/app
      - /app/node_modules
  dip:
    restart: always
    build:
      context: bundestag.io/dip
      target: build_stage
    command: yarn run dev
    volumes:
      - ./bundestag.io/dip:/app
      - /app/node_modules
    environment:
      - RATE_LIMIT=3
      - NODE_ENV=development
  democracy-api:
    build:
      context: democracy/api
      target: build_stage
    command: yarn run dev
    volumes:
      - ./democracy/api:/app
      - /app/node_modules
  democracy-web-app:
    build:
      context: democracy/web-app
      target: deps
    command: yarn run dev
    volumes:
      - ./democracy/web-app:/app
      - /app/node_modules
