version: "3.9"

services:
  bundestag-io:
    build:
      context: bundestag.io/server
      target: build_stage
    command: yarn run dev
    volumes:
      - ./bundestag.io/server:/app
  crawler:
    build:
      context: services/cron-jobs/crawler
      target: build_stage
