apiVersion: garden.io/v1
kind: Project
name: democracy-development

defaultEnvironment: local

variables:
  userNamespace: democracy-local

environments:
  - name: local
    defaultNamespace: ${var.userNamespace}
    variables:
      hostname: local.democracy-app.de
  - name: local-prod
    defaultNamespace: ${var.userNamespace}
    variables:
      hostname: local.democracy-app.de

providers:
  - name: local-kubernetes
    environments: [local, local-prod]
