apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: mananruck/bundestagio
      context: bundestag.io-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: mananruck/democracy-api
      context: democracy-app.de-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: mananruck/bundestagio-admin
      context: bundestag.io-admin
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: mananruck/democracy-app
      context: democracy-app.de
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
portForward:
  - resourceType: Deployment
    resourceName: democracy-mongo-depl
    port: 27017
    localPort: 27018
