apiVersion: skaffold/v2beta5
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/local.yaml
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
  artifacts:
    - image: docker.pkg.github.com/demokratie-live/bundestag.io/bundestag.io
      context: bundestag.io-api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: docker.pkg.github.com/demokratie-live/democracy-server/democracy-server
      context: democracy-app.de-api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: docker.pkg.github.com/demokratie-live/bundestag.io-admin/bundestag.io-admin
      context: bundestag.io-admin
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: docker.pkg.github.com/demokratie-live/democracy-desktop/democracy-desktop
      context: democracy-app.de
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: docker.pkg.github.com/demokratie-live/democracy-development/sync-named-polls
      context: ./services/cron-jobs/sync-named-polls
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: docker.pkg.github.com/demokratie-live/democracy-development/sync-procedures
      context: ./services/cron-jobs/sync-procedures
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: docker.pkg.github.com/demokratie-live/democracy-development/queue-pusch-conference-week
      context: ./services/cron-jobs/queue-pusch-conference-week
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: docker.pkg.github.com/demokratie-live/democracy-development/queue-pusch-vote-conference-week
      context: ./services/cron-jobs/queue-pusch-vote-conference-week
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
portForward:
  - resourceType: Deployment
    resourceName: democracy-mongo-depl
    port: 27017
    localPort: 27018
