apiVersion: skaffold/v2beta5
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/local.yaml
# deploy:
#   kustomize:
#     paths:
#       - infra/kustomize/overlays/local
build:
  local:
    push: false
  artifacts:
    - image: docker.pkg.github.com/demokratie-live/democracy-development/test-bundestag-api
      context: bundestag.io-api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: docker.pkg.github.com/demokratie-live/democracy-development/test-democracy-api
      context: democracy-app.de-api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: docker.pkg.github.com/demokratie-live/democracy-development/test-bundestag-admin
      context: bundestag.io-admin
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: docker.pkg.github.com/demokratie-live/democracy-development/test-democracy-app
      context: democracy-app.de
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
portForward:
  - resourceType: Deployment
    resourceName: democracy-mongo-depl
    port: 27017
    localPort: 27018
