apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-deputy-profiles
  labels:
    app: import-deputy-profiles
spec:
  schedule: '0 5 * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 86400
          containers:
            - name: import-deputy-profiles
              image: democracy/import-deputy-profiles:0.1.12
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: import-deputy-profiles
