apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base/cluster

patches:
  - bundestagio-depl.yaml
  - bundestagio-admin-depl.yaml
  - democracy-api-depl.yaml
  - democracy-app-depl.yaml
  - mongo-statefulset.yaml

resources:
  - ingress-srv.yaml

namespace: democracy-production
