apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundestagio-admin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bundestagio-admin
  template:
    metadata:
      labels:
        app: bundestagio-admin
    spec:
      containers:
        - name: bundestagio-admin
          image: docker.pkg.github.com/demokratie-live/bundestag.io-admin/bundestag.io-admin:2.1.2-dev
          livenessProbe:
            httpGet:
              path: /health-check
              port: 3000
            initialDelaySeconds: 180
            timeoutSeconds: 10
            periodSeconds: 600
          readinessProbe:
            httpGet:
              path: /health-check
              port: 3000
            timeoutSeconds: 10
            periodSeconds: 15
          envFrom:
            - configMapRef:
                name: bio-admin-config
            - secretRef:
                name: bio-admin-login
                optional: true
            - secretRef:
                name: bundestag-result-edit-token
                optional: true
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: bundestagio-admin-srv
spec:
  selector:
    app: bundestagio-admin
  ports:
    - name: bundestagio-admin
      protocol: TCP
      port: 3000
      targetPort: 3000
