apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup-push-queue-cronjob
spec:
  schedule: "3 12 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cleanup-push-queue
              image: docker.pkg.github.com/demokratie-live/democracy-development/cleanup-push-queue:0.0.1-gorush-alpha.0
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: DB_URL
                - name: BUNDESTAGIO_SERVER_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: BUNDESTAGIO_SERVER_URL
          imagePullSecrets:
            - name: regcred
