apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democracy-api
  template:
    metadata:
      labels:
        app: democracy-api
    spec:
      containers:
        - name: democracy-api
          image: docker.pkg.github.com/demokratie-live/democracy-server/democracy-server:0.2.30-dev
          envFrom:
            - configMapRef:
                name: democracy-api-config
            - secretRef:
                name: democracy-api-secrets
                optional: true
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: democracy-api-srv
spec:
  selector:
    app: democracy-api
  ports:
    - name: democracy-api
      protocol: TCP
      port: 3000
      targetPort: 3000
