apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democracy-app
  template:
    metadata:
      labels:
        app: democracy-app
    spec:
      containers:
        - name: democracy-app
          image: docker.pkg.github.com/demokratie-live/democracy-development/test-democracy-app:0.0.6
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 180
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            timeoutSeconds: 10
            periodSeconds: 15
          envFrom:
            - configMapRef:
                name: democracy-app-config
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: democracy-app-srv
spec:
  selector:
    app: democracy-app
  ports:
    - name: democracy-app
      protocol: TCP
      port: 3000
      targetPort: 3000
