apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: democracy-sync-procedures-cronjob
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: democracy-sync-procedures
              image: docker.pkg.github.com/demokratie-live/democracy-development/sync-procedures:0.1.12
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: DB_URL
                - name: BUNDESTAGIO_SERVER_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: BUNDESTAGIO_SERVER_URL
          imagePullSecrets:
            - name: regcred
