apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: democracy-sync-deputy-profiles-cronjob
spec:
  schedule: "3-59/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: democracy-sync-deputy-profiles
              image: democracy/sync-deputy-profiles:0.1.7
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: DB_URL
                - name: BUNDESTAGIO_SERVER_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: BUNDESTAGIO_SERVER_URL
