apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-procedures-cronjob
spec:
  schedule: '0 1 * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: import-procedures
              image: democracy/crawler:1.0.8
              envFrom:
                - configMapRef:
                    name: crawler-config
              command: ['yarn', 'run', 'start:import-procedures']
