apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-named-poll-deputies-cronjob
spec:
  schedule: "45 1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: import-named-poll-deputies
              image: docker.pkg.github.com/demokratie-live/democracy-development/import-named-poll-deputies:0.1.0
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
          imagePullSecrets:
            - name: regcred
