apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-deputy-profiles-period-18-cronjob
spec:
  schedule: '0 6 * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: import-deputy-profiles
              image: democracy/import-deputy-profiles:0.1.6
              env:
                - name: PERIOD
                  value: '18'
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
