apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-procedures-cronjob
spec:
  schedule: "0 1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: import-procedures
              image: docker.pkg.github.com/demokratie-live/democracy-development/import-procedures:0.1.3
              envFrom:
                - configMapRef:
                    name: import-procedures-config
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
          imagePullSecrets:
            - name: regcred
