apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-deputy-profiles-cronjob
spec:
  schedule: "0 4 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: import-deputy-profiles
              image: democracy/import-deputy-profiles:0.1.4
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
