apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-conference-week-details-cronjob
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: import-conference-week-details
              image: democracy/import-conference-week-details:0.1.9
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
