apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-deputy-profiles-cronjob
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: import-deputy-profiles
              image: docker.pkg.github.com/demokratie-live/democracy-development/import-deputy-profiles:0.1.0
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
          imagePullSecrets:
            - name: regcred
