apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-named-polls-cronjob
spec:
  schedule: "15 1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: import-named-polls
              image: democracy/import-named-polls:0.1.2
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
