apiVersion: batch/v1
kind: CronJob
metadata:
  name: index-sync-democracy-cronjob
spec:
  schedule: '0 7 * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: index-sync-democracy
              image: democracy/index-sync-democracy:0.1.1
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: DB_URL
