apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: queue-pushs-conference-week-cronjob
spec:
  schedule: "0 12 * * SUN"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: queue-pushs-conference-week
              image: docker.pkg.github.com/demokratie-live/democracy-development/queue-pushs-conference-week:0.1.6-gorush-alpha.0
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: DB_URL
                - name: BUNDESTAGIO_SERVER_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: BUNDESTAGIO_SERVER_URL
          imagePullSecrets:
            - name: regcred
