apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: queue-pushs-vote-conference-week-cronjob
spec:
  schedule: "0 2 * * MON-FRI"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: queue-pushs-vote-conference-week
              image: democracy/queue-pushs-vote-conference-week:0.1.3
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: DB_URL
                - name: BUNDESTAGIO_SERVER_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: BUNDESTAGIO_SERVER_URL
