apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: queue-pusch-conference-week-cronjob
spec:
  # schedule: "0 14 * * SUN"
  schedule: "3 1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: queue-pusch-conference-week
              image: docker.pkg.github.com/demokratie-live/democracy-development/queue-pusch-conference-week:0.1.1
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: DB_URL
                - name: BUNDESTAGIO_SERVER_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: BUNDESTAGIO_SERVER_URL
          imagePullSecrets:
            - name: regcred
