apiVersion: v1
data:
  BUNDESTAGIO_SERVER_URL: http://bundestagio-srv:3100/
  BUNDESTAGIO_SERVER_URL_CLIENT: http://bio-admin.develop/graphql
  NODE_ENV: development
kind: ConfigMap
metadata:
  name: bio-admin-config-h87b4fgb4h
---
apiVersion: v1
data:
  AUTH_JWT_SECRET: CHANGE_ME
  CRON_START_ON_INIT: "false"
  DB_URL: mongodb://democracy-mongo-srv:27017/bundestagio
  GRAPHIQL: /graphiql
  GRAPHQL_PATH: /
  NODE_ENV: development
  PERIODS: "19"
  SCRAPER_USER_AGEND: LOCAL-DEVELOPER
  VOYAGER: "true"
kind: ConfigMap
metadata:
  name: bio-api-config-b9m4dc95m9
---
apiVersion: v1
data:
  BUNDESTAGIO_SERVER_URL: http://bundestagio-srv:3100/
  CRON_START_ON_INIT: "false"
  DB_URL: mongodb://democracy-mongo-srv:27017/democracy
  DEBUG: "true"
  GRAPHIQL: "true"
  NODE_ENV: development
  STAGE: internal
kind: ConfigMap
metadata:
  name: democracy-api-config-mg5b2dd2d5
---
apiVersion: v1
data:
  GRAPHQL_URL: http://democracy-api.develop/
  GRAPHQL_URL_SERVER: http://democracy-api-srv:3000/
kind: ConfigMap
metadata:
  name: democracy-app-config-k4876hmgg9
---
apiVersion: v1
data:
  PERIODS: "[19]"
  SCRAPER_USER_AGEND: DEMOCRACY_LOCAL
kind: ConfigMap
metadata:
  name: import-procedures-config-6cghkt98bk
---
apiVersion: v1
data:
  APN_TOPIC: ""
  APPLE_TEAMID: ""
kind: ConfigMap
metadata:
  name: push-notifications-config-kbd9d2g2bd
---
apiVersion: v1
kind: Service
metadata:
  name: bundestagio-admin-srv
spec:
  ports:
    - name: bundestagio-admin
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: bundestagio-admin
---
apiVersion: v1
kind: Service
metadata:
  name: bundestagio-srv
spec:
  ports:
    - name: bundestagio
      port: 3100
      protocol: TCP
      targetPort: 3100
  selector:
    app: bundestagio
---
apiVersion: v1
kind: Service
metadata:
  name: democracy-mongo-srv
spec:
  ports:
    - name: db
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: democracy-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundestagio-admin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bundestagio-admin
  template:
    metadata:
      labels:
        app: bundestagio-admin
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: bio-admin-config-h87b4fgb4h
            - secretRef:
                name: bio-admin-login
                optional: true
            - secretRef:
                name: bundestag-result-edit-token
                optional: true
          image: docker.pkg.github.com/demokratie-live/bundestag.io-admin/bundestag.io-admin:2.1.6-dev
          name: bundestagio-admin
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundestagio-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bundestagio
  template:
    metadata:
      labels:
        app: bundestagio
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: bio-api-config-b9m4dc95m9
            - secretRef:
                name: bundestag-result-edit-token
                optional: true
          image: docker.pkg.github.com/demokratie-live/bundestag.io/bundestag.io:0.1.37-dev
          name: bundestagio
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democracy-mongo
  template:
    metadata:
      labels:
        app: democracy-mongo
    spec:
      containers:
        - image: mongo
          name: democracy-mongo
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-persistent-volume-claim
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-conference-week-details-cronjob
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      key: DB_URL
                      name: bio-api-config-b9m4dc95m9
              image: docker.pkg.github.com/demokratie-live/democracy-development/import-conference-week-details:0.1.8
              name: import-conference-week-details
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
  schedule: "*/30 * * * *"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-plenary-minutes-cronjob
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      key: DB_URL
                      name: bio-api-config-b9m4dc95m9
              image: docker.pkg.github.com/demokratie-live/democracy-development/import-plenary-minutes:0.1.0
              name: import-plenary-minutes
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
  schedule: 15 1 * * *
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-procedures-cronjob
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      key: DB_URL
                      name: bio-api-config-b9m4dc95m9
              envFrom:
                - configMapRef:
                    name: import-procedures-config-6cghkt98bk
              image: docker.pkg.github.com/demokratie-live/democracy-development/import-procedures:0.1.2
              name: import-procedures
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
  schedule: 0 1 * * *
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: ingress-service
spec:
  rules:
    - host: bundestagio.develop
      http:
        paths:
          - backend:
              serviceName: bundestagio-srv
              servicePort: 3100
            path: /?(.*)
    - host: bio-admin.develop
      http:
        paths:
          - backend:
              serviceName: bundestagio-admin-srv
              servicePort: 3000
            path: /?(.*)
    - host: democracy-api.develop
      http:
        paths:
          - backend:
              serviceName: democracy-api-srv
              servicePort: 3000
            path: /?(.*)
    - host: democracy-app.develop
      http:
        paths:
          - backend:
              serviceName: democracy-app-srv
              servicePort: 3000
            path: /?(.*)
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: democracy-mognodb-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/democracy-mongodb-volume
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
