apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodb.mongodb.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: Current state of the MongoDB deployment
    name: Phase
    type: string
  - JSONPath: .status.version
    description: Version of MongoDB server
    name: Version
    type: string
  group: mongodb.com
  names:
    kind: MongoDB
    listKind: MongoDBList
    plural: mongodb
    shortNames:
    - mdb
    singular: mongodb
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MongoDB is the Schema for the mongodbs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MongoDBSpec defines the desired state of MongoDB
          properties:
            featureCompatibilityVersion:
              description: FeatureCompatibilityVersion configures the feature compatibility
                version that will be set for the deployment
              type: string
            members:
              description: Members is the number of members in the replica set
              type: integer
            type:
              description: Type defines which type of MongoDB deployment the resource
                should create
              enum:
              - ReplicaSet
              type: string
            version:
              description: Version defines which version of MongoDB will be used
              type: string
          required:
          - type
          - version
          type: object
        status:
          description: MongoDBStatus defines the observed state of MongoDB
          properties:
            mongoUri:
              type: string
            phase:
              type: string
          required:
          - mongoUri
          - phase
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: mongodb-kubernetes-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - mongodb-kubernetes-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - mongodb.com
  resources:
  - '*'
  - mongodbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-kubernetes-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-kubernetes-operator
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator
---
apiVersion: v1
data:
  BUNDESTAGIO_SERVER_URL: http://bundestagio-srv:3100/
  BUNDESTAGIO_SERVER_URL_CLIENT: http://bio-admin.develop/graphql
  NODE_ENV: development
kind: ConfigMap
metadata:
  name: bio-admin-config-h87b4fgb4h
---
apiVersion: v1
data:
  AUTH_JWT_SECRET: CHANGE_ME
  CRON_CONFERENCEWEEKDETAILS: '*/15 * * * *'
  CRON_DEPUTY_PROFILES: 0 4 * * *
  CRON_NAMED_POLLS: 15 3 * * *
  CRON_NAMED_POLLS_DEPUTIES: 45 3 * * *
  CRON_PROCEDURES: 0 3 * * *
  CRON_START_ON_INIT: "false"
  DB_URL: mongodb://democracy-mongo-srv:27017/bundestagio
  GRAPHIQL: /graphiql
  GRAPHQL_PATH: /
  NODE_ENV: development
  PERIODS: "19"
  SCRAPER_USER_AGEND: LOCAL-DEVELOPER
  VOYAGER: "true"
kind: ConfigMap
metadata:
  name: bio-api-config-b9fbd5t7m9
---
apiVersion: v1
data:
  BUNDESTAGIO_SERVER_URL: http://bundestagio-srv:3100/
  CRON_DEPUTY_PROFILES: '*/15 * * * *'
  CRON_NAMED_POLLS: '*/15 * * * *'
  CRON_PROCEDURES: 0 */1 * * *
  CRON_SHEDULE_BIO_RESYNC: 55 3 * */1 *
  CRON_START_ON_INIT: "true"
  DB_URL: mongodb://democracy-mongo-srv:27017/democracy
  DEBUG: "true"
  GRAPHIQL: "true"
  NODE_ENV: development
  STAGE: internal
kind: ConfigMap
metadata:
  name: democracy-api-config-85gt54cf69
---
apiVersion: v1
data:
  GRAPHQL_URL: http://democracy-api.develop/
  GRAPHQL_URL_SERVER: http://democracy-api-srv:3000/
kind: ConfigMap
metadata:
  name: democracy-app-config-k4876hmgg9
---
apiVersion: v1
kind: Service
metadata:
  name: bundestagio-admin-srv
spec:
  ports:
  - name: bundestagio-admin
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: bundestagio-admin
---
apiVersion: v1
kind: Service
metadata:
  name: bundestagio-srv
spec:
  ports:
  - name: bundestagio
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: bundestagio
---
apiVersion: v1
kind: Service
metadata:
  name: democracy-api-srv
spec:
  ports:
  - name: democracy-api
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: democracy-api
---
apiVersion: v1
kind: Service
metadata:
  name: democracy-app-srv
spec:
  ports:
  - name: democracy-app
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: democracy-app
---
apiVersion: v1
kind: Service
metadata:
  name: democracy-mongo-srv
spec:
  ports:
  - name: db
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: democracy-mongo
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  ports:
  - name: client
    port: 4222
    protocol: TCP
    targetPort: 4222
  - name: monitoring
    port: 8222
    protocol: TCP
    targetPort: 8222
  selector:
    app: nats
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundestagio-admin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bundestagio-admin
  template:
    metadata:
      labels:
        app: bundestagio-admin
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: bio-admin-config-h87b4fgb4h
        - secretRef:
            name: bio-admin-login
            optional: true
        - secretRef:
            name: bundestag-result-edit-token
            optional: true
        image: docker.pkg.github.com/demokratie-live/bundestag.io-admin/bundestag.io-admin:2.1.2-dev
        livenessProbe:
          httpGet:
            path: /health-check
            port: 3000
          initialDelaySeconds: 180
          timeoutSeconds: 10
        name: bundestagio-admin
        readinessProbe:
          httpGet:
            path: /health-check
            port: 3000
          periodSeconds: 15
          timeoutSeconds: 10
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundestagio-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bundestagio
  template:
    metadata:
      labels:
        app: bundestagio
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: bio-api-config-b9fbd5t7m9
        - secretRef:
            name: bundestag-result-edit-token
            optional: true
        image: docker.pkg.github.com/demokratie-live/bundestag.io/bundestag.io:0.1.23-dev
        livenessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: 3100
          initialDelaySeconds: 60
          periodSeconds: 30
        name: bundestagio
        readinessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: 3100
          initialDelaySeconds: 30
          periodSeconds: 10
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democracy-api
  template:
    metadata:
      labels:
        app: democracy-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: democracy-api-config-85gt54cf69
        - secretRef:
            name: democracy-api-secrets
            optional: true
        image: docker.pkg.github.com/demokratie-live/democracy-server/democracy-server:0.2.3-dev
        livenessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: 3000
          periodSeconds: 180
        name: democracy-api
        readinessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: 3000
          initialDelaySeconds: 15
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democracy-app
  template:
    metadata:
      labels:
        app: democracy-app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: democracy-app-config-k4876hmgg9
        image: docker.pkg.github.com/demokratie-live/democracy-desktop/democracy-desktop:0.0.3-dev
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 180
          timeoutSeconds: 10
        name: democracy-app
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 15
          timeoutSeconds: 10
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democracy-mongo
  template:
    metadata:
      labels:
        app: democracy-mongo
    spec:
      containers:
      - image: mongo
        name: democracy-mongo
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-persistent-volume-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-kubernetes-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-kubernetes-operator
  template:
    metadata:
      labels:
        name: mongodb-kubernetes-operator
    spec:
      containers:
      - command:
        - mongodb-kubernetes-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: mongodb-kubernetes-operator
        - name: AGENT_IMAGE
          value: quay.io/mongodb/mongodb-agent:10.13.0.6199-1
        - name: PRE_STOP_HOOK_IMAGE
          value: quay.io/mongodb/mongodb-kubernetes-operator-pre-stop-hook:1.0.0
        image: quay.io/mongodb/mongodb-kubernetes-operator:0.0.6
        imagePullPolicy: Always
        name: mongodb-kubernetes-operator
      serviceAccountName: mongodb-kubernetes-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - args:
        - -p
        - "4222"
        - -m
        - "8222"
        - -hbi
        - 5s
        - -hbt
        - 5s
        - -hbf
        - "2"
        - -SD
        - -cid
        - ticketing
        image: nats-streaming:0.17.0
        name: nats
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: ingress-service
  namespace: monitoring
spec:
  rules:
  - host: monitoring.develop
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 80
        path: /?(.*)
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: ingress-service
spec:
  rules:
  - host: bundestagio.develop
    http:
      paths:
      - backend:
          serviceName: bundestagio-srv
          servicePort: 3100
        path: /?(.*)
  - host: bio-admin.develop
    http:
      paths:
      - backend:
          serviceName: bundestagio-admin-srv
          servicePort: 3000
        path: /?(.*)
  - host: democracy-api.develop
    http:
      paths:
      - backend:
          serviceName: democracy-api-srv
          servicePort: 3000
        path: /?(.*)
  - host: democracy-app.develop
    http:
      paths:
      - backend:
          serviceName: democracy-app-srv
          servicePort: 3000
        path: /?(.*)
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: example-mongodb
spec:
  members: 2
  resources:
    limits:
      cpu: 500m
      memory: 500M
    requests:
      cpu: 200m
      memory: 300M
  type: ReplicaSet
  version: 4.2.6
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: democracy-mognodb-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/democracy-mongodb-volume
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
