apiVersion: v1
kind: Service
metadata:
  name: gorush
  # namespace: gorush
  labels:
    app: gorush
    tier: frontend
spec:
  selector:
    app: gorush
    tier: frontend
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  #
  # if you want to expose the service to the outside (without a load balancer in front)
  # type: NodePort
  #
  # if you want gorush to be accessible only within the cluster
  # type: ClusterIP
  ports:
    - name: gorush
      protocol: TCP
      port: 80
      targetPort: 8088
