apiVersion: v1
kind: Service
metadata:
  name: gorush
  labels:
    app: gorush
    tier: frontend
spec:
  selector:
    app: gorush
  ports:
    - name: gorush
      protocol: TCP
      port: 8088
      targetPort: 8088
