apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gorush-configmap.yaml
  - gorush-deployment.yaml
  # - gorush-namespace.yaml
  - gorush-redis-deployment.yaml
  - gorush-redis-service.yaml
  - gorush-service.yaml

configMapGenerator:
  - name: gorush-config-yml
    files:
      - gorush-config.yaml
