apiVersion: v1
kind: Secret
metadata:
  name: zipkin
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
type: Opaque
data:
{{if eq .Values.storageMethod "cassandra3"}}
  cassandra.password: {{ b64enc .Values.cassandra.password }}
{{ end }}