env:
  global:
matrix:
  # sudo: required
  include:
  # test
  - os: linux
    language: node_js
    node_js: 12
    install:
    - yarn install
    before_script:
    - yarn build
    script:
    - yarn test
    after_script:
    - echo "SUCCESS: Finished Test-Build"
  # DeputyProfiles - Cron
  - os: linux #if: TRAVIS_EVENT_TYPE IN (cron)
    language: node_js
    node_js: 12
    install:
    - yarn install
    before_script:
    - yarn build
    - git clone https://github.com/bundestag/DeputyProfiles ./out/DeputyProfiles/
    script:
    - yarn start DeputyProfile ./out/DeputyProfiles
    #- yarn start NamedPoll ./out/NamedPolls
    #- yarn start NamedPollDeputy ./out/NamedPollDeputies
    after_script:
    - cd ./out/DeputyProfiles
    - git commit -a -m "Travis ${TRAVIS_BUILD_NUMBER} update"
    - git push master origin:master
    - echo "SUCCESS: Scraped DeputyProfiles & Pushed to Git"