apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundestagio-admin-depl
spec:
  template:
    spec:
      containers:
        - name: bundestagio-admin
          livenessProbe:
            httpGet:
              path: /health-check
              port: 3000
            initialDelaySeconds: 180
            timeoutSeconds: 10
            periodSeconds: 600
          readinessProbe:
            httpGet:
              path: /health-check
              port: 3000
            timeoutSeconds: 10
            periodSeconds: 15
