apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-app-depl
spec:
  template:
    spec:
      containers:
        - name: democracy-app
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 180
            timeoutSeconds: 30
            periodSeconds: 600
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 180
            timeoutSeconds: 60
            periodSeconds: 60
