apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-mongo
  labels:
    app: democracy-mongo
spec:
  selector:
    matchLabels:
      app: democracy-mongo
  template:
    metadata:
      labels:
        app: democracy-mongo
    spec:
      containers:
        - name: democracy-mongo
          image: mongo:4
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: '0.5'
              memory: '512Mi'
