apiVersion: v1
kind: Service
metadata:
  labels:
    app: democracy-mongo
  name: democracy-mongo
spec:
  type: ClusterIP
  selector:
    app: democracy-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
