apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-named-poll-deputies
  labels:
    app: import-named-poll-deputies
spec:
  schedule: '45 1 * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 86400
          containers:
            - name: import-named-poll-deputies
              image: democracy/import-named-poll-deputies:0.1.8
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: import-named-poll-deputies
