name: Docker Image

on:
  - push

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo dev)"
        id: extract_branch

      # - name: Extract branch name
      #   shell: bash
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch

      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - name: Extract repository name
        shell: bash
        run: echo "##[set-output name=REPOSITORY_NAME;]$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        id: extract_repository

      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ steps.extract_repository.outputs.REPOSITORY_NAME }}
          tags: ${{ steps.package-version.outputs.version }}-${{ steps.extract_branch.outputs.branch }}
