apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundestagio-depl
spec:
  selector:
    matchLabels:
      app: bundestagio
  template:
    spec:
      containers:
        - name: bundestagio
          image: docker.pkg.github.com/demokratie-live/bundestag.io/bundestag.io:0.1.20-dev
          resources:
            limits:
              memory: "500Mi"
              cpu: "300m"
