apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundestagio-depl
spec:
  selector:
    matchLabels:
      app: bundestagio
  template:
    spec:
      containers:
        - name: bundestagio
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "400Mi"
              cpu: "250m"
