apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-api-depl
spec:
  selector:
    matchLabels:
      app: democracy-api
  template:
    spec:
      containers:
        - name: democracy-api
          image: docker.pkg.github.com/demokratie-live/democracy-server/democracy-server:0.2.0-dev
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
