apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-api-depl
spec:
  selector:
    matchLabels:
      app: democracy-api
  template:
    spec:
      containers:
        - name: democracy-api
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
