apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base/main
  - ../../../base/cluster
patches:
  - bundestagio-depl.yaml
  - bundestagio-admin-depl.yaml
  - democracy-api-depl.yaml
  - democracy-app-depl.yaml
