apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: bundestagio.develop
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: bundestagio-srv
                port:
                  number: 3100
    - host: bio-admin.develop
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: bundestagio-admin-srv
                port:
                  number: 3000
    - host: democracy-api.develop
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: democracy-api-srv
                port:
                  number: 3000
    - host: democracy-app.develop
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: democracy-app-srv
                port:
                  number: 3000
