apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democracy-api
  template:
    metadata:
      labels:
        app: democracy-api
    spec:
      containers:
        - name: democracy-api
          image: docker.pkg.github.com/demokratie-live/democracy-development/test-democracy-api:0.0.5
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_DB_URL
            - name: BUNDESTAGIO_SERVER_URL
              value: "http://bundestagio-srv:3100/"
            - name: STAGE
              value: internal
            - name: DEBUG
              value: "true"
            - name: GRAPHIQL
              value: "true"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: democracy-api-srv
spec:
  selector:
    app: democracy-api
  ports:
    - name: democracy-api
      protocol: TCP
      port: 3000
      targetPort: 3000
