apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democracy-app
  template:
    metadata:
      labels:
        app: democracy-app
    spec:
      containers:
        - name: democracy-app
          image: mananruck/democracy-app
          env:
            - name: GRAPHQL_URL
              value: "http://democracy-api-srv:3000/"
            - name: GRAPHQL_URL_SERVER
              value: "http://democracy.develop/"
---
apiVersion: v1
kind: Service
metadata:
  name: democracy-app-srv
spec:
  selector:
    app: democracy-app
  ports:
    - name: democracy-app
      protocol: TCP
      port: 3000
      targetPort: 3000
