name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        yarn install
        yarn run bootstrap
    - name: Run linter
      run: yarn run lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        yarn install
        yarn run bootstrap
    - name: Run tests
      run: yarn run test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        yarn install
        yarn run bootstrap
    - name: Build packages
      run: yarn run build
