name: Docker – shedule-bio-resync

on:
  push:
    paths:
      - "services/cron-jobs/shedule-bio-resync/**"
    # branches:
    #   - master

jobs:
  build:
    name: Docker – shedule-bio-resync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
        with:
          path: "./services/cron-jobs/shedule-bio-resync"

      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/shedule-bio-resync
          path: ./services/cron-jobs/shedule-bio-resync
          tags: ${{ steps.package-version.outputs.version }}
