name: Docker – shedule-bio-resync

on:
  push:
    paths:
      - "services/cron-jobs/shedule-bio-resync/**"
    branches:
      - "master"
    tags:
      - "shedule-bio-resync@v*"
  pull_request:
    paths:
      - "services/cron-jobs/shedule-bio-resync/**"
    branches:
      - "master"

jobs:
  push-shedule-bio-resync:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: democracy/shedule-bio-resync
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,asref=foo,pattern=shedule-bio-resync@v(\d+.\d+.\d+),group=1
            type=semver,pattern={{version}},use=foo
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: services/cron-jobs/shedule-bio-resync
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
