name: Pull Request

on:
  pull_request:
    paths:
      - 'services/**'
      - 'bundestag.io/**'
      - 'democracy/**'
    branches:
      - 'master'

jobs:
  analyse-changed-services:
    runs-on: ubuntu-latest
    outputs:
      CHANGED_PACKAGES: ${{ steps.changed-packages.outputs.CHANGED_PACKAGES }}
    steps:
      - name: Analyze changed services
        run: |
          pnpm list -r --json --filter "...[$SINCE]" --changed-files-ignore-pattern="**/(garden.yml|.dockerignore)" | jq '[.[] | select(.private == false) | {name, path}]' > ./tmp.json
          CHANGED_PACKAGES=$(jq '[.[] | .name]' ./tmp.json)
          echo CHANGED_PACKAGES=$CHANGED_PACKAGES  >> $GITHUB_OUTPUT
          echo CHANGED_PACKAGES=$CHANGED_PACKAGES
        id: changed-packages
        env:
          SINCE: master

  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    needs: analyse-changed-services
    with:
      changedPackages: ${{fromJson(needs.analyse-changed-services.outputs.CHANGED_PACKAGES)}}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
