name: Pull Request

on:
  pull_request:
    paths:
      - 'services/**'
    branches:
      - 'master'

jobs:
  analyse-changed-services:
    uses: ./.github/workflows/get-changed-services.yaml

  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    needs: analyse-changed-services
    with:
      changedPackages: ${{ needs.analyse-changed-services.outputs.CHANGED_PACKAGES }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
