on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  changeFinder:
    runs-on: ubuntu-latest
    outputs:
      since: ${{ steps.interrogate.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - id: interrogate
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const {execSync} = require('child_process');
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner,
              repo
            });
            console.log(`latest release: ${JSON.stringify(latestRelease.data)}`);
            execSync('git pull --tags -q');
            execSync(`git reset --hard ${latestRelease.data.tag_name}`);
            const sha = execSync('git rev-parse HEAD').toString().trim();
            console.log(`sha: ${sha}`)
            return sha

      - run: |
          echo "since=${{ steps.interrogate.outputs.result }}"
  analyse-changed-packages:
    needs: [changeFinder]
    uses: demokratie-live/democracy-development/.github/workflows/analyse-changed-packages.yaml@master
    with:
      since: ${{ needs.changeFinder.outputs.since }}

  release-please:
    runs-on: ubuntu-latest
    environment: docker
    needs: [changeFinder, analyse-changed-packages]
    if: ${{ needs.analyse-changed-packages.outputs.changed != '[]' && needs.analyse-changed-packages.outputs.changed != '' }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.analyse-changed-packages.outputs.changed)}}
    steps:
      - name: get directory for package
        id: get-directory
        run: |
          # Variablen setzen
          matrix_package="${{ matrix.package }}"
          changed_packages_json='${{ needs.analyse-changed-packages.outputs.changedPackages }}'

          # Verzeichnis mit jq finden
          directory=$(echo "$changed_packages_json" | jq -r --arg package "$matrix_package" '.[] | select(.package == $package) | .directory')

          # Ausgabe
          echo "$directory"
          echo "directory=$directory" >> $GITHUB_OUTPUT

      - uses: google-github-actions/release-please-action@v3
        with:
          path: ${{ steps.get-directory.outputs.directory }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          package-name: ${{ matrix.package }}
          command: github-release
          bootstrap-sha: 416a41c6c73b0ed1e145ce798dce2cca51518721
