name: 🧑‍🌾 QA
on:
  push:
  workflow_dispatch:

jobs:
  QA:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🚀 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: 🔧 Enable Corepack
        run: corepack enable

      - name: 📦 Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🧪 Lint
        run: pnpm lint

      - name: 🧪 Test
        run: pnpm test

      - name: 🏗️ Build
        run: pnpm build
