apiVersion: apps/v1
kind: Deployment
metadata:
  name: democracy-app-depl
spec:
  selector:
    matchLabels:
      app: democracy-app
  template:
    spec:
      containers:
        - name: democracy-app
          image: docker.pkg.github.com/demokratie-live/democracy-desktop/democracy-desktop:0.0.3-dev
          resources:
            limits:
              memory: "300Mi"
              cpu: "500m"
            requests:
              memory: "300Mi"
              cpu: "500m"
