apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - internal.api.democracy-app.de
        - internal.democracy-app.de
        - internal.qr.democracy-app.de
        - internal.api.bundestag.io
        - internal.admin.bundestag.io
      secretName: democracy-internal-tls
  rules:
    - host: internal.api.democracy-app.de
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: democracy-api-srv
              servicePort: 3000
    - host: internal.democracy-app.de
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: democracy-app-srv
              servicePort: 3000
    - host: internal.qr.democracy-app.de
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: qr-code-handler-srv
              servicePort: 3000
    - host: internal.api.bundestag.io
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: bundestagio-srv
              servicePort: 3100
    - host: internal.admin.bundestag.io
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: bundestagio-admin-srv
              servicePort: 3000
